#Django deployment
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: memodir-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memodir-app-container
  template:
    metadata:
      labels:
        app: memodir-app-container
        tier: backend
    spec:
      volumes:
      - name: memodir-db-volume-mount
        persistentVolumeClaim:
          claimName: memodir-file-volume-claim
      imagePullSecrets:
      - name: regcred
      containers:
      - name: memodir-app
        #image: memodir.azurecr.io/cv_web:0.1
        image: seawaywen/cv:0.1
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
        volumeMounts:
        - name: memodir-db-volume-mount
          mountPath: /var/lib/busybox
        env:
        - name: DB_NAME
          value: memodir
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: db_password
        - name: GOOGLE_TAG_MANAGER_ID
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: google_tag_manager_id
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: email_host
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: email_host_user
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memodir-credentials
              key: email_host_password

        - name: DB_SERVICE
          value: memodir-db-service
        - name: DB_PORT
          value: "5432"
        - name: DEBUG
          value: "False"
