language: python
os: linux
node_js:
  - 8.9.1
python:
  - "3.5"
services:
  - postgresql
env:
  -DJANGO=2.0.4 DB=postgresql
install:
  - pip install -r requirements.txt -r requirements-devel.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd static_src && yarn && yarn build && cd ..
script:
  - PYTHONPATH=src:. DJANGO_SETTINGS_MODULE=django_project.settings python django_project/manage.py test
