version: '3'

services:
  db:
    container_name: memodir-db-service
    image: 'postgres:10.4'
    restart: always
    environment:
      POSTGRES_DB: memodir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  web:
    container_name: memodir-app-service
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile_prod
    env_file: ./.docker/app/.env
    #volumes:
    #  - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    container_name: memodir-nginx-service
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  pgdata:
