#DB Deployment
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: memodir-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memodir-db-container
  template:
    metadata:
      labels:
        app: memodir-db-container
        tier: backend
    spec:
      volumes:
      - name: memodir-db-volume-mount
        persistentVolumeClaim:
          claimName: memodir-data-claim
      containers:
      - name: memodir-db
        image: postgres:10.4
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: memodir-db-volume-mount
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: memodir-db-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: memodir-db-credentials
                key: password
          - name: POSTGRES_DB
            value: memodir
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata


---

# db service
kind: Service
apiVersion: v1
metadata:
  name: memodir-db-service
spec:
  selector:
    app: memodir-db-container
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
