---
#Persistent volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: memodir-file-volume
  labels:
    name: memodir-file-volume
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
      path: "/mnt/data"

---
#Persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: memodir-file-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
